really store and update byte arrays
So far we only support f32 fields, and the node layout isn't in
the imagined form.

The result doesn't work with ipfs dag get anymore though:

Error: failed to decode Protocol Buffers: incorrectly formatted merkledag node:
  unmarshal failed. proto: PBNode: wiretype end group for non-group

So maybe the block_put function doesn't expect cbor and labels it
as protobuf instead.  It also still returns old-school base58 CIDs.